spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: postgres
  jpa:
    hibernate.ddl-auto: create-drop
springdoc:
  swagger-ui:
    enabled: false