spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: postgres #${password}
  jpa:
    hibernate.ddl-auto: create-drop #validate
springdoc:
  swagger-ui:
    enabled: false