app:
  scheduling:
    enabled: true
    optimization: true
    priceIncreasePercentage: ${scheduling.priceIncreasePercentage:10}
    fixedDelay: ${scheduling.fixedDelay:10000}
spring:
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: false
  datasource:
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: postgres #${password}
  jpa:
    hibernate.ddl-auto: create #create